// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ConfigGetAvailableProfiles():Promise<any>;

export function ServicesGetSettings():Promise<models.Settings>;

export function ServicesSetSelectedProfile(arg1:string):Promise<models.Settings>;
