// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigGetAvailableProfiles() {
  return window['go']['app']['App']['ConfigGetAvailableProfiles']();
}

export function ServicesGetSettings() {
  return window['go']['app']['App']['ServicesGetSettings']();
}

export function ServicesSetSelectedProfile(arg1) {
  return window['go']['app']['App']['ServicesSetSelectedProfile'](arg1);
}
